#!/usr/bin/env python3
"""Summarize panel generation without invoking models or changing the art store.

Run from the repository root: image_generation_status.py report|write|check.
"""
from __future__ import annotations

import argparse
from collections import Counter

import panelart
import produce
import storyboards
import textimage

OUTPUT = produce.ROOT / "IMAGE-GENERATION-STATUS.md"


def cell(value: str) -> str:
    return " ".join(value.split()).replace("|", "\\|")


def render() -> str:
    slots = produce.all_slots()
    scripts = {script.id: script for script in textimage.book_scripts()}
    records = panelart.load(refresh=True)
    scenes = storyboards.load()["scenes"]
    available = {
        slot.id: [v for v in records.get(slot.id, []) if v.path.is_file()]
        for slot in slots
    }
    ready = {slot.id for slot in slots if slot.art() is not None}
    selected = {key: panelart.pick(variants) for key, variants in available.items()}
    approved = {
        key for key, winner in selected.items()
        if winner and winner.stage == "final" and winner.status == panelart.CHOSEN
    }
    boards = {
        key for key, variants in available.items()
        if any(v.stage == "storyboard" and v.status != panelart.REJECTED for v in variants)
    }
    providers = Counter(
        v.provider or "unspecified" for variants in available.values() for v in variants
        if v.stage in ("refined", "final") and v.status != panelart.REJECTED
    )
    missing = sorted(v.file for variants in records.values() for v in variants
                     if not v.path.is_file())
    orphaned = sorted(set(records) - set(available))
    lines = [
        "# Panel image generation status", "",
        "Generated by `python3 scripts/image_generation_status.py write`. Do not edit by hand.", "",
        "## Current coverage", "",
        f"- Required reader image slots: **{len(slots)}** across **{len(scripts)}** story pages.",
        f"- Refined/final artwork available: **{len(ready)}**.",
        f"- Still need refinement or generation: **{len(slots) - len(ready)}**.",
        f"- Selected, explicitly chosen final artwork: **{len(approved)}**.",
        f"- Slots with storyboard scene records: **{sum(s.id in scenes for s in slots)}**.",
        f"- Slots with non-rejected storyboard files: **{len(boards)}**.", "",
        "The remaining queue uses the same rule as `produce.py status`: a slot needs work when",
        "it has no existing, non-rejected refined/final variant. A chosen storyboard still needs",
        "refinement. Refined candidates count as available, but are not automatically approved.",
        "Grouped script grids count as one reader image slot. Controlled diagrams and interfaces",
        "can be finished without an image model; this queue does not prescribe a generation route.", "",
        "## By chapter", "",
        "| Chapter | Slots | Refined/final available | Need work | Chosen final |",
        "| --- | ---: | ---: | ---: | ---: |",
    ]
    for chapter in dict.fromkeys(s.chapter for s in slots):
        keys = {s.id for s in slots if s.chapter == chapter}
        lines.append(f"| {chapter} | {len(keys)} | {len(keys & ready)} | "
                     f"{len(keys - ready)} | {len(keys & approved)} |")
    lines += ["", "## Remaining work by page", "",
              "Each key below is a required image slot without refined/final artwork.", "",
              "| Script | Chapter | Slots needing work | Storyboard files / remaining |",
              "| --- | --- | --- | ---: |"]
    for page, script in scripts.items():
        pending = [s.id for s in slots if s.page == page and s.id not in ready]
        if pending:
            keys = ", ".join(f"`{key}`" for key in pending)
            lines.append(f"| [{page}: {cell(script.title)}](content/pages/{page}.md) | "
                         f"{script.chapter} | {keys} | "
                         f"{sum(key in boards for key in pending)} / {len(pending)} |")
    if len(ready) == len(slots):
        lines.append("| None | — | — | — |")
    lines += ["", "## Existing refined/final work", "",
              "These slots are skipped by default production runs. Inspect candidates before",
              "choosing or marking final; use `--force` for an additional generation attempt.", "",
              "| Slot | Production candidate | Stage / approval | Currently displayed |",
              "| --- | --- | --- | --- |"]
    for slot in slots:
        if slot.id not in ready:
            continue
        winner = panelart.pick([v for v in available[slot.id]
                                if v.stage in ("refined", "final")])
        display = selected[slot.id]
        lines.append(f"| `{slot.id}` | [{winner.variant}: {cell(winner.provider)}]({winner.file}) | "
                     f"{winner.stage} / {winner.status} | "
                     f"{display.variant}: {display.stage} / {display.status} |")
    lines += ["", "## Available refined/final variants by provider", "",
              "Counts include all non-rejected versions, so one slot can contribute several variants.", "",
              "| Provider | Variants |", "| --- | ---: |"]
    lines += [f"| {cell(provider)} | {count} |" for provider, count in sorted(providers.items())]
    lines += ["", "## Inventory findings", "",
              f"- Registered files missing from disk: **{len(missing)}**.",
              f"- Registered panel keys outside the current reader slots: **{len(orphaned)}**."]
    lines += [f"- Missing: `{path}`" for path in missing]
    lines += [f"- Non-current key: `{key}`" for key in orphaned]
    lines += ["", "## Refresh and next steps", "",
              "Run from the repository root:", "", "```sh",
              "python3 scripts/image_generation_status.py write",
              "python3 scripts/image_generation_status.py check", "```", "",
              "Refresh after generation, import, curation, stage changes, or page/panel identity changes.",
              "`report` prints the current summary without writing; `check` fails if this file is stale.",
              "The output is deterministic: unchanged inputs do not create timestamp-only edits.", "",
              "Sources: canonical scripts through the shared reader/production slot model,",
              "`data/storyboards.json`, and `data/panel-art.tsv` with file-existence checks.",
              "An unregistered image is not counted when the art table exists, matching production.",
              "After importing files, run `python3 scripts/panelart.py scan` before refreshing.",
              "The append-only generation log is historical evidence, not the current inventory;",
              "its old identifiers and experiments are not treated as completed slots.", "",
              "For a queued key, inspect the script and storyboard, then use",
              "`python3 scripts/produce.py plan --slot NNN-II` to plan a local attempt.",
              "Planning does not generate images. Runner readiness, visual quality, and source drift",
              "are outside this census; validate boards with",
              "`python3 scripts/storyboards.py check --complete` and follow the",
              "[storyboard workflow](design/storyboard-workflow.md) for refinement, import, and approval.", ""]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("command", choices=("report", "write", "check"))
    args = parser.parse_args()
    expected = render()
    if args.command == "report":
        print(expected, end="")
    elif args.command == "write":
        OUTPUT.write_text(expected, encoding="utf-8")
        print(f"Wrote {OUTPUT.name}")
    elif not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != expected:
        print("Image generation status is stale. Run python3 scripts/image_generation_status.py write")
        return 1
    else:
        print("Image generation status is current.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
